### your site title here

title: Penworks OER
author:
    name: Pen Lister
    # email: 
description: >- # this means to ignore newlines until "baseurl:"
  This is a repository of Open Educational Resources created over the past 10 years by Pen Lister. 
  Content can be viewed from this Github Pages site, or using the front end available from my website at 
  https://penworks.net. All content is licensed under a CC BY SA NC license.
tagline: Open Education for all
baseurl: "/oerv2" # the subpath of your site, e.g. /blog
url: "https://penworks.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:day/:title:output_ext
#permalink: /:title:output_ext

# shorturls
#--------------
# subpagesurl: "/subpages/"
imagesurl: "/assets/images/"
thumbsurl: "/assets/thumbs/"
slidesurl: "/assets/slides/"
#pdfdocurl: "/assets/pdfdocs/"
#pdfsurl: "assets/slides"

### let's use the minima theme (see https://github.com/jekyll/minima)

theme: minima
#remote_theme: jekyll/minima

### exclude the instructions / write-up in the README.md

exclude:
- README.md

#collections
#-----------
collections:
      teaching:
          layout: base
          output: true
          permalink: /:collection/:name
      projects:
          layout: base
          output: true
          permalink: /:collection/:name
      talks:
          layout: base
          output: true
          permalink: /:collection/:name 

# Generate social links in footer.
minima:
  social_links:
     - { platform: rss, user_url: "https://mysite.com/feed.xml" }
     - { platform: github, user_url: "https://github.com/Penworks" }
     - { platform: mastodon, user_url: "https://mastodon.social/@DrPen" } 

  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
